[package]
name = "particle-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
piston_window = "0.146.0"
rand = "0.9.2"
find_folder = "0.3.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
